export const Members = [
  {
    id: 1,
    member_name: "Orn SivEng",
    member_title: "Frontend Developer",
    member_image: "/avatar.jpg",
    member_github: "https://github.com/SivEngOrn",
    member_linkedin: "https://www.linkedin.com/in/siveng-orn/",
  },
  {
    id: 1,
    member_name: "Orn SivEng",
    member_title: "Frontend Developer",
    member_image: "/avatar.jpg",
    member_github: "https://github.com/SivEngOrn",
    member_linkedin: "https://www.linkedin.com/in/siveng-orn/",
  },
  {
    id: 1,
    member_name: "Orn SivEng",
    member_title: "Frontend Developer",
    member_image: "/avatar.jpg",
    member_github: "https://github.com/SivEngOrn",
    member_linkedin: "https://www.linkedin.com/in/siveng-orn/",
  },
  {
    id: 1,
    member_name: "Orn SivEng",
    member_title: "Frontend Developer",
    member_image: "/avatar.jpg",
    member_github: "https://github.com/SivEngOrn",
    member_linkedin: "https://www.linkedin.com/in/siveng-orn/",
  },
  {
    id: 1,
    member_name: "Orn SivEng",
    member_title: "Frontend Developer",
    member_image: "/avatar.jpg",
    member_github: "https://github.com/SivEngOrn",
    member_linkedin: "https://www.linkedin.com/in/siveng-orn/",
  },
  {
    id: 1,
    member_name: "Orn SivEng",
    member_title: "Frontend Developer",
    member_image: "/avatar.jpg",
    member_github: "https://github.com/SivEngOrn",
    member_linkedin: "https://www.linkedin.com/in/siveng-orn/",
  },
  {
    id: 1,
    member_name: "Orn SivEng",
    member_title: "Frontend Developer",
    member_image: "/avatar.jpg",
    member_github: "https://github.com/SivEngOrn",
    member_linkedin: "https://www.linkedin.com/in/siveng-orn/",
  },
];