export const Members = [
  {
    id: 1,
    member_name: "Orn SivEng",
    member_title: "Team leader",
    member_image: "/avatar.jpg",
    member_github: "https://github.com/SivEngOrn",
    member_linkedin: "https://www.linkedin.com/in/siveng-orn/",
  },
  {
    id: 1,
    member_name: "Sroeun Doungchan",
    member_title: "Fullstack Developer",
    member_image: "/avatar.jpg",
    member_github: "https://github.com/SivEngOrn",
    member_linkedin: "https://www.linkedin.com/in/siveng-orn/",
  },
  {
    id: 1,
    member_name: "Ney Senrith",
    member_title: "Fullstack Developer",
    member_image: "/avatar.jpg",
    member_github: "https://github.com/SivEngOrn",
    member_linkedin: "https://www.linkedin.com/in/siveng-orn/",
  },
  {
    id: 1,
    member_name: "Lock Borethdevid",
    member_title: "Frontend Developer",
    member_image: "/avatar.jpg",
    member_github: "https://github.com/SivEngOrn",
    member_linkedin: "https://www.linkedin.com/in/siveng-orn/",
  },
  {
    id: 1,
    member_name: "Oun Visidhreach",
    member_title: "Frontend Developer",
    member_image: "/avatar.jpg",
    member_github: "https://github.com/SivEngOrn",
    member_linkedin: "https://www.linkedin.com/in/siveng-orn/",
  },
  {
    id: 1,
    member_name: "San Vivorth",
    member_title: "Backend Developer",
    member_image: "/avatar.jpg",
    member_github: "https://github.com/SivEngOrn",
    member_linkedin: "https://www.linkedin.com/in/siveng-orn/",
  },
  {
    id: 1,
    member_name: "Sor Panharith",
    member_title: "Backend Developer",
    member_image: "/avatar.jpg",
    member_github: "https://github.com/SivEngOrn",
    member_linkedin: "https://www.linkedin.com/in/siveng-orn/",
  },
];